
trigger:
- master
- development

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/OtisElevatorDevice.ElevatorDeviceTests/ReturnDataServiceTests.cs'
    arguments: '--configuration $(buildConfiguration)'
